blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/
    about: This is for development related issues. For support and technical issues, please come to our Discord server.